// ignore_for_file: duplicate_ignore, public_member_api_docs, sort_constructors_first, directives_ordering, dangling_library_doc_comments, library_prefixes, constant_identifier_names, depend_on_referenced_packages
// test/ecdsa_key_parity_test.dart
//
// Parity test for lib/src/crypto/ecdsa_key.dart against a real NIST P-256
// key generated by Go's crypto/ecdsa + crypto/x509
// (go-ipfs-reference/ecdsa_vectors/main.go), self-verified in Go before
// being copied here. Go's ecdsa.Sign uses a randomized nonce (not
// RFC6979), so unlike the RSA/Secp256k1 vectors this proves parity via
// cross-verification rather than a byte-identical signature: Dart must
// accept a real Go-produced signature, and DER/SEC1 key encodings must
// round-trip exactly.
import 'dart:typed_data';

import 'package:transpiled_libp2p/transpiled_libp2p.dart';
import 'package:test/test.dart';

Uint8List _fromHex(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

const _ecPrivateDerHex =
    '307702010104208eecfc53e7823be45c8ed74d61996a6f579ba0605368fd8ec2809e81346'
    '02c14a00a06082a8648ce3d030107a14403420004371121e4ab8f065e94ffbbbb8e9d23f'
    'b1595cda6d5254fa54e865e744d88dbbd85c4bd735119cb6fa973381b16be6d9c1c54e23'
    'e5f806706cdbb9216fb1010c4';

const _pkixPublicDerHex =
    '3059301306072a8648ce3d020106082a8648ce3d03010703420004371121e4ab8f065e94'
    'ffbbbb8e9d23fb1595cda6d5254fa54e865e744d88dbbd85c4bd735119cb6fa973381b16'
    'be6d9c1c54e23e5f806706cdbb9216fb1010c4';

const _messageHex =
    '68656c6c6f2066726f6d20646172745f697066732045434453412074657374';

const _signatureDerHex =
    '3045022100c3468614e82af510ae5df201b3dfc2b2ed043f16977f49e70982f785c8996'
    '91d02200381be33d5e0c81b2954f554f9311832566b8cee43d35484a876c576036584c6';

void main() {
  group('ECDSA (P-256) -- real Go-generated vector', () {
    test('unmarshal SEC1 private key, re-marshal matches byte-for-byte', () {
      final der = _fromHex(_ecPrivateDerHex);
      final priv = unmarshalEcdsaPrivateKey(der);
      expect(priv.type, equals(KeyType.ecdsa));
      expect(priv.raw(), equals(der));
    });

    test('unmarshal PKIX public key, re-marshal matches byte-for-byte', () {
      final der = _fromHex(_pkixPublicDerHex);
      final pub = unmarshalEcdsaPublicKey(der);
      expect(pub.type, equals(KeyType.ecdsa));
      expect(pub.raw(), equals(der));
    });

    test("private key's derived public key matches the PKIX vector", () {
      final priv = unmarshalEcdsaPrivateKey(_fromHex(_ecPrivateDerHex));
      expect(priv.getPublic().raw(), equals(_fromHex(_pkixPublicDerHex)));
    });

    test('verifies a real Go-produced ECDSA/SHA-256 signature', () async {
      final pub = unmarshalEcdsaPublicKey(_fromHex(_pkixPublicDerHex));
      final ok = await pub.verify(_fromHex(_messageHex), _fromHex(_signatureDerHex));
      expect(ok, isTrue);
    });

    test('rejects a tampered signature', () async {
      final pub = unmarshalEcdsaPublicKey(_fromHex(_pkixPublicDerHex));
      final sig = _fromHex(_signatureDerHex);
      sig[sig.length - 1] ^= 0xff;
      final ok = await pub.verify(_fromHex(_messageHex), sig);
      expect(ok, isFalse);
    });

    test('rejects a signature over the wrong message', () async {
      final pub = unmarshalEcdsaPublicKey(_fromHex(_pkixPublicDerHex));
      final ok = await pub.verify(_fromHex('00' * 20), _fromHex(_signatureDerHex));
      expect(ok, isFalse);
    });

    test("Dart's own signature over the real key/message verifies", () async {
      final priv = unmarshalEcdsaPrivateKey(_fromHex(_ecPrivateDerHex));
      final sig = await priv.sign(_fromHex(_messageHex));
      final ok = await priv.getPublic().verify(_fromHex(_messageHex), sig);
      expect(ok, isTrue);
    });
  });

  group('ECDSA (P-256) -- generation and round-trip', () {
    test('a freshly generated key signs and verifies its own signature', () async {
      final priv = generateEcdsaKeyPair();
      final data = Uint8List.fromList('round trip me'.codeUnits);
      final sig = await priv.sign(data);
      final ok = await (priv.getPublic() as EcdsaPublicKey).verify(data, sig);
      expect(ok, isTrue);
    });

    test('marshal -> unmarshal round-trips a freshly generated key', () async {
      final priv = generateEcdsaKeyPair();
      final reparsed = unmarshalEcdsaPrivateKey(priv.raw());
      expect(reparsed.raw(), equals(priv.raw()));
      expect(reparsed.getPublic().raw(), equals(priv.getPublic().raw()));

      final data = Uint8List.fromList('cross-instance check'.codeUnits);
      final sig = await priv.sign(data);
      final ok = await reparsed.getPublic().verify(data, sig);
      expect(ok, isTrue);
    });

    test('rejects a public key on the wrong curve OID', () {
      // secp256k1's OID substituted for P-256's inside an otherwise
      // well-formed PKIX SubjectPublicKeyInfo.
      final tampered = _fromHex(_pkixPublicDerHex);
      // The curve OID bytes '2a8648ce3d030107' (prime256v1) sit right
      // before the uncompressed point; flip a byte inside them so the OID
      // no longer matches, without touching the point bytes.
      final oidIndex = _indexOfSubsequence(tampered, _fromHex('2a8648ce3d030107'));
      expect(oidIndex, isNonNegative);
      tampered[oidIndex] ^= 0xff;
      expect(() => unmarshalEcdsaPublicKey(tampered), throwsFormatException);
    });
  });
}

int _indexOfSubsequence(Uint8List haystack, Uint8List needle) {
  for (var i = 0; i + needle.length <= haystack.length; i++) {
    var match = true;
    for (var j = 0; j < needle.length; j++) {
      if (haystack[i + j] != needle[j]) {
        match = false;
        break;
      }
    }
    if (match) return i;
  }
  return -1;
}
