// test/ed25519_key_parity_test.dart
//
// Parity test for lib/src/crypto/ed25519_key.dart against a real key
// generated by Go's stdlib crypto/ed25519
// (go-ipfs-reference/ed25519_vectors/main.go). Proves the raw private
// key format (64-byte seed||publicKey, matching Go's ed25519.PrivateKey)
// and EdDSA signatures are byte-compatible with go-libp2p's
// Ed25519PrivateKey/Ed25519PublicKey.
import 'dart:typed_data';

import 'package:transpiled_libp2p/transpiled_libp2p.dart';
import 'package:test/test.dart';

Uint8List _fromHex(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

const _rawPrivateHex =
    'c6c066262b9b4c416994f5bb0c3a91cf69fd7218602510a20b12903d7ec6077a'
    'f422b499f662ceb548cc2dd1625819703597117263ed75f56e7cf9e6a9269f33';

const _rawPublicHex =
    'f422b499f662ceb548cc2dd1625819703597117263ed75f56e7cf9e6a9269f33';

const _messageHex =
    '68656c6c6f2066726f6d20646172745f6970667320456432353531392074657374';

const _signatureHex =
    'bac3d1e2fe854b44cf538a252c525bfda453bb25c4a98e2e829e5c46ed56a2239f2e16c0d6'
    'b7e12e119e69f72aa84a315403357f6e271ddd1968f9d0126c9a04';

void main() {
  group('Ed25519 -- real Go-generated vector', () {
    test('unmarshal 64-byte private key, re-marshal matches byte-for-byte', () async {
      final raw = _fromHex(_rawPrivateHex);
      final priv = await unmarshalEd25519PrivateKey(raw);
      expect(priv.type, equals(KeyType.ed25519));
      expect(priv.raw(), equals(raw));
    });

    test('unmarshal 32-byte public key, re-marshal matches byte-for-byte', () {
      final raw = _fromHex(_rawPublicHex);
      final pub = unmarshalEd25519PublicKey(raw);
      expect(pub.type, equals(KeyType.ed25519));
      expect(pub.raw(), equals(raw));
    });

    test("private key's derived public key matches the vector", () async {
      final priv = await unmarshalEd25519PrivateKey(_fromHex(_rawPrivateHex));
      expect(priv.getPublic().raw(), equals(_fromHex(_rawPublicHex)));
    });

    test('verifies a real Go-produced EdDSA signature', () async {
      final pub = unmarshalEd25519PublicKey(_fromHex(_rawPublicHex));
      final ok = await pub.verify(_fromHex(_messageHex), _fromHex(_signatureHex));
      expect(ok, isTrue);
    });

    test('rejects a tampered signature', () async {
      final pub = unmarshalEd25519PublicKey(_fromHex(_rawPublicHex));
      final sig = _fromHex(_signatureHex);
      sig[0] ^= 0xff;
      final ok = await pub.verify(_fromHex(_messageHex), sig);
      expect(ok, isFalse);
    });

    test("Dart's own EdDSA signature over the real key/message matches Go's", () async {
      final priv = await unmarshalEd25519PrivateKey(_fromHex(_rawPrivateHex));
      final sig = await priv.sign(_fromHex(_messageHex));
      // EdDSA is deterministic, so this must match Go's signature exactly.
      expect(sig, equals(_fromHex(_signatureHex)));
    });

    test('rejects a private key with a mismatched redundant public key', () async {
      final tampered = Uint8List.fromList([
        ..._fromHex(_rawPrivateHex),
        ...List<int>.filled(32, 0), // wrong "redundant" pubkey copy
      ]);
      await expectLater(unmarshalEd25519PrivateKey(tampered), throwsFormatException);
    });
  });

  group('Ed25519 -- generation and round-trip', () {
    test('a freshly generated key signs and verifies its own signature', () async {
      final priv = await generateEd25519KeyPair();
      final data = Uint8List.fromList('round trip me'.codeUnits);
      final sig = await priv.sign(data);
      final ok = await priv.getPublic().verify(data, sig);
      expect(ok, isTrue);
    });

    test('marshal -> unmarshal round-trips a freshly generated key', () async {
      final priv = await generateEd25519KeyPair();
      final reparsed = await unmarshalEd25519PrivateKey(priv.raw());
      expect(reparsed.raw(), equals(priv.raw()));
      expect(reparsed.getPublic().raw(), equals(priv.getPublic().raw()));
    });

    test('rejects a private key of the wrong length', () async {
      await expectLater(unmarshalEd25519PrivateKey(Uint8List(10)), throwsFormatException);
    });

    test('ed25519KeyPairFromSeed is deterministic and matches the seed embedded in raw()', () async {
      final seed = Uint8List.fromList(List<int>.generate(32, (i) => i * 7 % 256));
      final a = await ed25519KeyPairFromSeed(seed);
      final b = await ed25519KeyPairFromSeed(seed);
      expect(a.raw(), equals(b.raw()));
      expect(a.raw().sublist(0, 32), equals(seed));

      final data = Uint8List.fromList('seeded key check'.codeUnits);
      final sig = await a.sign(data);
      expect(await b.getPublic().verify(data, sig), isTrue);
    });

    test('ed25519KeyPairFromSeed rejects a seed of the wrong length', () async {
      await expectLater(ed25519KeyPairFromSeed(Uint8List(31)), throwsArgumentError);
    });
  });
}
