// test/transport/noise/noise_state_test.dart
//
// Byte-for-byte parity test against a real Noise_XX_25519_ChaChaPoly_SHA256
// handshake vector, generated by flynn/noise's own vectorgen tool (the
// actual Go library go-libp2p's noise transport depends on) --
// go-ipfs-reference/noise_vectors/all_vectors.txt, the entry with a
// prologue and payloads (no PSK). This proves the hand-rolled Dart Noise
// state machine in lib/src/transport/noise/noise_state.dart produces wire
// bytes a real go-libp2p peer would accept, not just internally consistent
// output.
import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';
import 'package:test/test.dart';
import 'package:transpiled_libp2p/transpiled_libp2p.dart';

Uint8List _fromHex(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

Future<NoiseKeyPair> _fixedKeyPair(String hexPrivate) async {
  final priv = _fromHex(hexPrivate);
  final kp = await X25519().newKeyPairFromSeed(priv);
  final pub = await kp.extractPublicKey();
  return NoiseKeyPair(
    privateKeyBytes: priv,
    publicKeyBytes: Uint8List.fromList(pub.bytes),
  );
}

void main() {
  group('Noise_XX_25519_ChaChaPoly_SHA256 -- real flynn/noise vector', () {
    // go-ipfs-reference/noise_vectors/all_vectors.txt, line 17106 block
    // (no PSK, with prologue, with payloads).
    const initStaticPriv =
        '000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f';
    const respStaticPriv =
        '0102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f20';
    const genInitEphemeral =
        '202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f';
    const genRespEphemeral =
        '4142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f60';
    const prologueHex = '6e6f74736563726574';

    const msg0Payload = '746573745f6d73675f30';
    const msg0Ciphertext =
        '358072d6365880d1aeea329adf9121383851ed21a28e3b75e965d0d2cd166254'
        '746573745f6d73675f30';
    const msg1Payload = '746573745f6d73675f31';
    const msg1Ciphertext =
        '64b101b1d0be5a8704bd078f9895001fc03e8e9f9522f188dd128d9846d48466'
        '3414af878d3e46a2f58911a816d6e8346d4ea17a6f2a0bb4ef4ed56c133cff45'
        '45958c588d17d6373e0c1dcfa3755d37f50cbca216483ac56bcc98f5095870aa'
        '814ba40c08079c11f087';
    const msg2Payload = '746573745f6d73675f32';
    const msg2Ciphertext =
        '87f864c11ba449f46a0a4f4e2eacbb7b0457784f4fca1937f572c93603e9c4d9'
        'c1e9a1a313d02b78871cfd178a521a4c7c7377a2f4f9144b2f0ccedc84d379151'
        'b466741e4b266db6023';
    const msg3Payload = '79656c6c6f777375626d6172696e65'; // "yellowsubmarine"
    const msg3Ciphertext =
        'a52ef02ba60e12696d1d6b9ef4245c88fca757b6134ad6e76b56e310a6adf6';
    const msg4Payload = '7375626d6172696e6579656c6c6f77'; // "submarineyellow"
    const msg4Ciphertext =
        '2445aa438ebd649281c636cc7269ca82f1d9023d72520943aeabf909cdf521';

    test('every handshake and transport message matches byte-for-byte', () async {
      final initStatic = await _fixedKeyPair(initStaticPriv);
      final respStatic = await _fixedKeyPair(respStaticPriv);
      final initEphemeral = await _fixedKeyPair(genInitEphemeral);
      final respEphemeral = await _fixedKeyPair(genRespEphemeral);
      final prologue = _fromHex(prologueHex);

      final init = await HandshakeState.initialize(
        initiator: true,
        staticKeyPair: initStatic,
        prologue: prologue,
        ephemeralKeyGenerator: () async => initEphemeral,
      );
      final resp = await HandshakeState.initialize(
        initiator: false,
        staticKeyPair: respStatic,
        prologue: prologue,
        ephemeralKeyGenerator: () async => respEphemeral,
      );

      // msg_0: initiator -> responder, "-> e"
      final (m0, split0) = await init.writeMessage(_fromHex(msg0Payload));
      expect(split0, isNull);
      expect(m0, equals(_fromHex(msg0Ciphertext)));
      final (p0, rSplit0) = await resp.readMessage(m0);
      expect(rSplit0, isNull);
      expect(p0, equals(_fromHex(msg0Payload)));

      // msg_1: responder -> initiator, "<- e, ee, s, es"
      final (m1, split1) = await resp.writeMessage(_fromHex(msg1Payload));
      expect(split1, isNull);
      expect(m1, equals(_fromHex(msg1Ciphertext)));
      final (p1, iSplit1) = await init.readMessage(m1);
      expect(iSplit1, isNull);
      expect(p1, equals(_fromHex(msg1Payload)));
      expect(init.remoteStaticKey, equals(respStatic.publicKeyBytes));

      // msg_2: initiator -> responder, "-> s, se" -- handshake completes.
      final (m2, iSplit2) = await init.writeMessage(_fromHex(msg2Payload));
      expect(iSplit2, isNotNull);
      expect(m2, equals(_fromHex(msg2Ciphertext)));
      final (p2, rSplit2) = await resp.readMessage(m2);
      expect(rSplit2, isNotNull);
      expect(p2, equals(_fromHex(msg2Payload)));
      expect(resp.remoteStaticKey, equals(initStatic.publicKeyBytes));

      // vectorgen's own transport-phase vectors (msg_3/msg_4) are *not* a
      // cross-party exchange: they come straight from whichever side
      // wrote the last handshake message (the initiator here) calling
      // Encrypt on its own two split CipherStates in turn --
      // vectorgen.go's `cs0, cs1 = writer.WriteMessage(...)` followed by
      // `cs0.Encrypt(payload0)` then `cs1.Encrypt(payload1)`, with no
      // corresponding Decrypt call on the other side at all. So both
      // messages are encrypted from iSplit2 directly.
      final (initCs1, initCs2) = iSplit2!;

      final m3 = await initCs1.encryptWithAd(
        Uint8List(0),
        _fromHex(msg3Payload),
      );
      expect(m3, equals(_fromHex(msg3Ciphertext)));

      final m4 = await initCs2.encryptWithAd(
        Uint8List(0),
        _fromHex(msg4Payload),
      );
      expect(m4, equals(_fromHex(msg4Ciphertext)));

      // Not part of the vector, but confirms the responder's Split()
      // independently derives the identical two keys from the same final
      // chaining key: decrypting each message with the responder's
      // same-index CipherState (fresh, nonce 0, matching the encrypting
      // side) must recover the original payload.
      final (respCs1, respCs2) = rSplit2!;
      final p3 = await respCs1.decryptWithAd(Uint8List(0), m3);
      expect(p3, equals(_fromHex(msg3Payload)));
      final p4 = await respCs2.decryptWithAd(Uint8List(0), m4);
      expect(p4, equals(_fromHex(msg4Payload)));
    });
  });

  group('HandshakeState -- self-interop sanity', () {
    test('two fresh sessions complete a handshake and exchange data', () async {
      final aStatic = await generateNoiseKeyPair();
      final bStatic = await generateNoiseKeyPair();
      final prologue = Uint8List.fromList(utf8.encode('dart_ipfs-noise-test'));

      final a = await HandshakeState.initialize(
        initiator: true,
        staticKeyPair: aStatic,
        prologue: prologue,
      );
      final b = await HandshakeState.initialize(
        initiator: false,
        staticKeyPair: bStatic,
        prologue: prologue,
      );

      final (m0, _) = await a.writeMessage(Uint8List(0));
      await b.readMessage(m0);
      final (m1, _) = await b.writeMessage(Uint8List(0));
      await a.readMessage(m1);
      final (m2, aSplit) = await a.writeMessage(Uint8List(0));
      final (_, bSplit) = await b.readMessage(m2);

      expect(aSplit, isNotNull);
      expect(bSplit, isNotNull);
      expect(a.remoteStaticKey, equals(bStatic.publicKeyBytes));
      expect(b.remoteStaticKey, equals(aStatic.publicKeyBytes));

      // a is the initiator, so its enc is cs1 (Split()'s first output);
      // the same value is b's dec, since go-libp2p's handshake.go assigns
      // the responder dec=cs1/enc=cs2 -- the *opposite* mapping from the
      // initiator, using the same underlying (cs1, cs2) pair both sides
      // derive identically from the shared final chaining key.
      final (aEnc, _) = aSplit!;
      final (bDec, _) = bSplit!;
      final ciphertext = await aEnc.encryptWithAd(
        Uint8List(0),
        Uint8List.fromList(utf8.encode('hello over noise')),
      );
      final plaintext = await bDec.decryptWithAd(Uint8List(0), ciphertext);
      expect(utf8.decode(plaintext), equals('hello over noise'));
    });
  });
}
