// ignore_for_file: duplicate_ignore, public_member_api_docs, sort_constructors_first, directives_ordering, dangling_library_doc_comments, library_prefixes, constant_identifier_names, depend_on_referenced_packages
// test/rsa_key_parity_test.dart
//
// Parity test for lib/src/crypto/rsa_key.dart against a real RSA-2048 key
// generated by Go's crypto/rsa + crypto/x509
// (go-ipfs-reference/noise_vectors/rsa_vectors.go), self-verified in Go
// before being copied here (round-tripped through x509.ParsePKCS1PrivateKey
// and independently checked with rsa.VerifyPKCS1v15). Proves this port
// produces/accepts the exact PKCS1/PKIX DER bytes and PKCS1v1.5 signatures
// a real go-libp2p peer would.
import 'dart:typed_data';

import 'package:transpiled_libp2p/transpiled_libp2p.dart';
import 'package:test/test.dart';

Uint8List _fromHex(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

const _pkcs1PrivateDerHex =
    '308204a30201000282010100ea0a1909618e3bb50febc31c695a97309a5f9f758b687a5350a0'
    '2c2b3144e9ad7520ebdafcafe1b824e82763cc4f3d673adbe07dec6d84029b39746d2e6e3fdf'
    '562ad14198652707844128c779067b513190970958847149ce23305ca7b1b413785278baf7da'
    'e91377c57f5c68d68bd4ae32e6ebdfa131de0350aad443f80ec4f4449cf97c5d702547523704'
    '1faa688e8b7dcd7db2237c016e0d98f824730f008dad3df2c5be40382b43f630fd2847292c47'
    '94d75c80728ffee525f2c9946d435b4db6591fde64231a3c13de7593a5652296093416a5ac8d'
    'a4bfd5bafd0d9b52f8d4f56510d4da3bcdcb8ac9dae9e3d818ebc1e58d3f42667865bfc22a9b'
    'e1cd020301000102820100375dcc2e7bf5ba0a4b89eace7dde00866efed02a6ea078cfdcf307'
    '7ff057ed302bd56df69070cb6554d5d6fbb509c9ecf1efb25c17e290a84d307a6a99e15b1aea'
    'b796697e33efd7c761e2d3cdbdcace9a7b2a3ffbc0d94c2c880698e4d31556c5d03cdf7e633b'
    '606fa5394c13412e335242987e9498fdc317e5ad8429d0352dcef8d3c85e43438da593cb8a1d'
    '5220a1560484cf24e2707b9b100e495a8c775ff95d07351dd4764b7b8660926957d4359a9bb5'
    'b516fb5a79e9b1d935b64c44a575ddecbf5ace8d92f937a343af27c904398bdd9e8dae3c6f30'
    '56ebebd4d2fa4705b19fbd4f15345f99b9d67108ee1b6e472e1bf9854dc25498a654d7a8cc92'
    '0102818100ec3e9c1091dcb35f18ff9f36f7968acc73ae0713b67495a9fcad4aa1fbe1021f79'
    '27e5a2e32cf31fb90933d40453df1cf264a08f54d3e71d58e7e53279cbb2ce3ce636be3a7e1a'
    'fb1314f20e4eff5a5c4bbcba6bc9325ddd8f1353c1367cc36593628703e9f86e67e5c4045092'
    '524291029755550d7f1f46e055efb77e35094902818100fd9c4838aae7bdd0dcaa057986b839'
    'e73be8b1bf280a7c2b658f2d6bf0baf7cd84963e62d2d27cea2ed4950aa52d36f3696b455fdc'
    '9a8e4458a6d09c20327cdf69e81da2b26c09327bbfe45586d1b6e3cf73364e0f6b36f408e450'
    '433547f11fdb65a90c1a236e63ebd61e77b573e4710ce0ebc72a4c08231c81310855ad786502'
    '81802075f5e1bcf9135874c9e2e99d997cd6dcea43a4acc45630363ce56d5e7bab5c01bcbeab'
    'e405301ee2c0e5f332e9075625e437bf9a0b47cd5b82f99636f00b50954398b008bf7d1b94a2'
    'a323de2cee1092838b25f64e4a6180204ab8d8b0c9f4720ceeba55f2c1d0dadc552f70fb8694'
    '004425007bcb44d3eb4d4393f5ee79a90281805c00b9168db19a63cdd98438ed0da23be7b8e7'
    'daa00d05b4bc982f732c16b7d4ffd77d745e64ebda0cf923c483dd9e44b9a6a7b93a0f7bb301'
    'b22a95a8fc87de88ce230a25ce199c0dd6b45fee93dfd44f2acdb58dd468502975a2446f6cd4'
    'e5a8b2fd9b9d53e3352e9633e15b9b5a7144a9c7ff2db1fd75b75e8aca2a42cf1d02818100c1'
    'dea6bb56e747fd25e3a3c407557e34a8990dab4fd3054de29d12fd1f5d1cfd729fc67ba843ce'
    '10a9dbda5de591da4c7a7442a59b019918c6f163555208efc6968b0efeabccaf15a26d76a61b'
    '85f43bd7afdb4635ff2a0a9ca69f5bd7aace119527c3566f3f0e1d2b10c99f33adf3c5ce6461'
    '8d71ade16f128d82c261125afb';

const _pkixPublicDerHex =
    '30820122300d06092a864886f70d01010105000382010f003082010a0282010100ea0a190961'
    '8e3bb50febc31c695a97309a5f9f758b687a5350a02c2b3144e9ad7520ebdafcafe1b824e827'
    '63cc4f3d673adbe07dec6d84029b39746d2e6e3fdf562ad14198652707844128c779067b5131'
    '90970958847149ce23305ca7b1b413785278baf7dae91377c57f5c68d68bd4ae32e6ebdfa131'
    'de0350aad443f80ec4f4449cf97c5d7025475237041faa688e8b7dcd7db2237c016e0d98f824'
    '730f008dad3df2c5be40382b43f630fd2847292c4794d75c80728ffee525f2c9946d435b4db6'
    '591fde64231a3c13de7593a5652296093416a5ac8da4bfd5bafd0d9b52f8d4f56510d4da3bcd'
    'cb8ac9dae9e3d818ebc1e58d3f42667865bfc22a9be1cd0203010001';

const _messageHex =
    '68656c6c6f2066726f6d20646172745f69706673205253412074657374';

const _signatureHex =
    '3f2b0f207f9f7c29c858214c7f5894af78c45c6c90dfa05ff5e9ffe4e82a25a3fad295826866'
    'bc860a063088a4193216807b710da3390be5b2cedcb80a9b8474600ed10af9d3b1a7c2d8836e'
    'eca36e5a9f5a4e0e51bbc30831a21b4daa86df5c0595299acc0872bf6c35bc671067ff9ed5c8'
    '321fd815ec62e8d09ef6a5bc9116c79c03b6cf287ff3a4320e83167a9039b1a7fb700588b707'
    'f5891fc968804865af2be8aedbe4ebdf4e3b0e809a31804cd46a9160252456fbe18ae6836f2e'
    '3001d93ef8494aeda12beeb323eb8659f1cfa7842ecf00b80122e39b914f38ecbd2b559baf28'
    'ee9a7c3fac37607d131144127e11b9ad665274cc455586a4f2cb4d6b';

void main() {
  group('RSA -- real Go-generated vector', () {
    test('unmarshal PKCS1 private key, re-marshal matches byte-for-byte', () {
      final der = _fromHex(_pkcs1PrivateDerHex);
      final priv = unmarshalRsaPrivateKey(der);
      expect(priv.type, equals(KeyType.rsa));
      expect(priv.raw(), equals(der));
    });

    test('unmarshal PKIX public key, re-marshal matches byte-for-byte', () {
      final der = _fromHex(_pkixPublicDerHex);
      final pub = unmarshalRsaPublicKey(der);
      expect(pub.type, equals(KeyType.rsa));
      expect(pub.raw(), equals(der));
    });

    test("private key's derived public key matches the PKIX vector", () {
      final priv = unmarshalRsaPrivateKey(_fromHex(_pkcs1PrivateDerHex));
      expect(priv.getPublic().raw(), equals(_fromHex(_pkixPublicDerHex)));
    });

    test('verifies a real go-libp2p-style SHA256/PKCS1v1.5 signature', () async {
      final pub = unmarshalRsaPublicKey(_fromHex(_pkixPublicDerHex));
      final ok = await pub.verify(
        _fromHex(_messageHex),
        _fromHex(_signatureHex),
      );
      expect(ok, isTrue);
    });

    test('rejects a tampered signature', () async {
      final pub = unmarshalRsaPublicKey(_fromHex(_pkixPublicDerHex));
      final sig = _fromHex(_signatureHex);
      sig[0] ^= 0xff;
      final ok = await pub.verify(_fromHex(_messageHex), sig);
      expect(ok, isFalse);
    });

    test('rejects a signature over the wrong message', () async {
      final pub = unmarshalRsaPublicKey(_fromHex(_pkixPublicDerHex));
      final ok = await pub.verify(
        _fromHex('00' * 30),
        _fromHex(_signatureHex),
      );
      expect(ok, isFalse);
    });

    test("signs with Dart's own key, and Dart's own verify accepts it", () async {
      final priv = unmarshalRsaPrivateKey(_fromHex(_pkcs1PrivateDerHex));
      final sig = await priv.sign(_fromHex(_messageHex));
      // A real PKCS1v1.5 signature over a fixed key+message is
      // deterministic (no randomization in the padding scheme), so this
      // must match Go's own signature exactly.
      expect(sig, equals(_fromHex(_signatureHex)));
    });
  });

  group('RSA -- generation and round-trip', () {
    test('a freshly generated key signs and verifies its own signature', () async {
      final priv = generateRsaKeyPair(minRsaKeyBits);
      final data = Uint8List.fromList('round trip me'.codeUnits);
      final sig = await priv.sign(data);
      final ok = await (priv.getPublic() as RsaPublicKey).verify(data, sig);
      expect(ok, isTrue);
    });

    test('rejects a key smaller than minRsaKeyBits', () {
      expect(() => generateRsaKeyPair(1024), throwsArgumentError);
    });

    test('marshal -> unmarshal round-trips a freshly generated key', () async {
      final priv = generateRsaKeyPair(minRsaKeyBits);
      final reparsed = unmarshalRsaPrivateKey(priv.raw());
      expect(reparsed.raw(), equals(priv.raw()));
      expect(reparsed.getPublic().raw(), equals(priv.getPublic().raw()));

      final data = Uint8List.fromList('cross-instance check'.codeUnits);
      final sig = await priv.sign(data);
      final ok = await reparsed.getPublic().verify(data, sig);
      expect(ok, isTrue);
    });
  });
}
