// ignore_for_file: duplicate_ignore, public_member_api_docs, sort_constructors_first, directives_ordering, dangling_library_doc_comments, library_prefixes, constant_identifier_names, depend_on_referenced_packages
// test/secp256k1_key_parity_test.dart
//
// Parity test for lib/src/crypto/secp256k1_key.dart against a real key
// generated by github.com/decred/dcrd/dcrec/secp256k1/v4 + /ecdsa
// (go-ipfs-reference/secp256k1_vectors/main.go) -- the exact library
// go-libp2p's core/crypto/secp256k1.go wraps. Proves this port produces/
// accepts the same raw key encodings and DER signatures a real go-libp2p
// peer would.
import 'dart:typed_data';

import 'package:transpiled_libp2p/transpiled_libp2p.dart';
import 'package:test/test.dart';

Uint8List _fromHex(String hex) {
  final out = Uint8List(hex.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(hex.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

const _rawPrivateHex =
    '9d8070e0f91ae20a3779686a14c84eae5eaf89e83448b1b0115a496eaef82232';

const _rawPublicCompressedHex =
    '029a270aa3997079bdcecd3641cd3aaa9672a5c5e00d87dec1b620bdf342897809';

const _messageHex =
    '68656c6c6f2066726f6d20646172745f6970667320736563703235366b312074657374';

const _signatureDerHex =
    '3045022100a4ef7da8174ae44e360f906976ec8034555721935e6a761773940a2ae90d41'
    '4002202d7b3501df711a70a49a69f60326c700e0e511cf9aca04d69bf216a8815554e3';

void main() {
  group('Secp256k1 -- real Go-generated vector', () {
    test('unmarshal 32-byte private key, re-marshal matches byte-for-byte', () {
      final raw = _fromHex(_rawPrivateHex);
      final priv = unmarshalSecp256k1PrivateKey(raw);
      expect(priv.type, equals(KeyType.secp256k1));
      expect(priv.raw(), equals(raw));
    });

    test('unmarshal compressed public key, re-marshal matches byte-for-byte', () {
      final raw = _fromHex(_rawPublicCompressedHex);
      final pub = unmarshalSecp256k1PublicKey(raw);
      expect(pub.type, equals(KeyType.secp256k1));
      expect(pub.raw(), equals(raw));
    });

    test("private key's derived public key matches the vector", () {
      final priv = unmarshalSecp256k1PrivateKey(_fromHex(_rawPrivateHex));
      expect(priv.getPublic().raw(), equals(_fromHex(_rawPublicCompressedHex)));
    });

    test('verifies a real dcrd RFC6979/DER signature', () async {
      final pub = unmarshalSecp256k1PublicKey(_fromHex(_rawPublicCompressedHex));
      final ok = await pub.verify(_fromHex(_messageHex), _fromHex(_signatureDerHex));
      expect(ok, isTrue);
    });

    test('rejects a tampered signature', () async {
      final pub = unmarshalSecp256k1PublicKey(_fromHex(_rawPublicCompressedHex));
      final sig = _fromHex(_signatureDerHex);
      sig[sig.length - 1] ^= 0xff;
      final ok = await pub.verify(_fromHex(_messageHex), sig);
      expect(ok, isFalse);
    });

    test('rejects a signature over the wrong message', () async {
      final pub = unmarshalSecp256k1PublicKey(_fromHex(_rawPublicCompressedHex));
      final ok = await pub.verify(_fromHex('00' * 20), _fromHex(_signatureDerHex));
      expect(ok, isFalse);
    });

    test("Dart's own RFC6979 signature over the real key/message", () async {
      final priv = unmarshalSecp256k1PrivateKey(_fromHex(_rawPrivateHex));
      final sig = await priv.sign(_fromHex(_messageHex));
      // Both go-libp2p (via dcrd) and this port use RFC6979-deterministic
      // nonce generation, so signing the same key+message twice -- once in
      // Go, once here -- should reliably produce the same DER signature.
      expect(sig, equals(_fromHex(_signatureDerHex)));
    });
  });

  group('Secp256k1 -- generation and round-trip', () {
    test('a freshly generated key signs and verifies its own signature', () async {
      final priv = generateSecp256k1KeyPair();
      final data = Uint8List.fromList('round trip me'.codeUnits);
      final sig = await priv.sign(data);
      final ok = await (priv.getPublic() as Secp256k1PublicKey).verify(data, sig);
      expect(ok, isTrue);
    });

    test('signing the same key/message twice is deterministic', () async {
      final priv = generateSecp256k1KeyPair();
      final data = Uint8List.fromList('determinism check'.codeUnits);
      final sig1 = await priv.sign(data);
      final sig2 = await priv.sign(data);
      expect(sig1, equals(sig2));
    });

    test('marshal -> unmarshal round-trips a freshly generated key', () async {
      final priv = generateSecp256k1KeyPair();
      final reparsed = unmarshalSecp256k1PrivateKey(priv.raw());
      expect(reparsed.raw(), equals(priv.raw()));
      expect(reparsed.getPublic().raw(), equals(priv.getPublic().raw()));

      final data = Uint8List.fromList('cross-instance check'.codeUnits);
      final sig = await priv.sign(data);
      final ok = await reparsed.getPublic().verify(data, sig);
      expect(ok, isTrue);
    });

    test('rejects a private key of the wrong length', () {
      expect(() => unmarshalSecp256k1PrivateKey(Uint8List(16)), throwsFormatException);
    });
  });
}
