name: transpiled_go_codec_dagpb
description: Port of go-codec-dagpb wire codec.
version: 0.1.0
publish_to: none
environment:
  sdk: ^3.10.0
dependencies:
  boilerplate:
    path: ../boilerplate
  transpiled_protobuf:
    path: ../transpiled_protobuf
  transpiled_cid:
    path: ../transpiled_cid
  transpiled_ipld_prime:
    path: ../transpiled_ipld_prime
dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0
