// lib/src/crypto/secp256k1_key.dart
//
// Port of go-libp2p's core/crypto Secp256k1 support (core/crypto/
// secp256k1.go), which itself is a thin wrapper over
// github.com/decred/dcrd/dcrec/secp256k1/v4: raw private keys are the
// 32-byte big-endian scalar, raw public keys are SEC1-compressed (33
// bytes), and signatures are RFC6979-deterministic ECDSA over SHA-256,
// DER-encoded with the S component canonicalized to the lower half of
// the curve order (to match `Signature.Serialize()`/`ParseDERSignature`).
//
// Verified against a real key/signature generated by
// github.com/decred/dcrd/dcrec/secp256k1/v4 + /ecdsa
// (go-ipfs-reference/secp256k1_vectors/main.go) -- see
// test/secp256k1_key_parity_test.dart.
import 'dart:math' show Random;
import 'dart:typed_data';

import 'package:pointycastle/asn1.dart';
import 'package:pointycastle/export.dart' as pc;

import 'key_types.dart';

final pc.ECDomainParameters _params = pc.ECCurve_secp256k1();

/// A Secp256k1 private key, per go-libp2p's `core/crypto`
/// `Secp256k1PrivateKey`.
class Secp256k1PrivateKey extends PrivKey {
  Secp256k1PrivateKey._(this._key, this._public);

  /// Wraps an already-parsed pointycastle EC private key.
  factory Secp256k1PrivateKey.fromPointyCastle(pc.ECPrivateKey key) {
    final q = (_params.G * key.d!)!;
    final pub = pc.ECPublicKey(q, _params);
    return Secp256k1PrivateKey._(key, Secp256k1PublicKey.fromPointyCastle(pub));
  }

  final pc.ECPrivateKey _key;
  final Secp256k1PublicKey _public;

  @override
  KeyType get type => KeyType.secp256k1;

  @override
  PubKey getPublic() => _public;

  @override
  Uint8List raw() => _encodeFixed32(_key.d!);

  @override
  Future<Uint8List> sign(Uint8List data) async {
    final signer = pc.ECDSASigner(pc.SHA256Digest(), pc.HMac(pc.SHA256Digest(), 64))
      ..init(true, pc.PrivateKeyParameter<pc.ECPrivateKey>(_key));
    final sig = signer.generateSignature(data) as pc.ECSignature;
    return _encodeDerSignature(sig.normalize(_params));
  }
}

/// A Secp256k1 public key, per go-libp2p's `core/crypto`
/// `Secp256k1PublicKey`.
class Secp256k1PublicKey extends PubKey {
  Secp256k1PublicKey._(this._key);

  /// Wraps an already-parsed pointycastle EC public key.
  factory Secp256k1PublicKey.fromPointyCastle(pc.ECPublicKey key) =>
      Secp256k1PublicKey._(key);

  final pc.ECPublicKey _key;

  @override
  KeyType get type => KeyType.secp256k1;

  @override
  Uint8List raw() => _key.Q!.getEncoded(true);

  @override
  Future<bool> verify(Uint8List data, Uint8List signature) async {
    final pc.ECSignature sig;
    try {
      sig = _decodeDerSignature(signature);
    } on FormatException {
      return false;
    }
    final signer = pc.ECDSASigner(pc.SHA256Digest())
      ..init(false, pc.PublicKeyParameter<pc.ECPublicKey>(_key));
    return signer.verifySignature(data, sig);
  }
}

/// Generates a fresh Secp256k1 key pair, per go-libp2p's
/// `GenerateSecp256k1Key`.
Secp256k1PrivateKey generateSecp256k1KeyPair() {
  final keyGen = pc.ECKeyGenerator()
    ..init(pc.ParametersWithRandom(pc.ECKeyGeneratorParameters(_params), _secureRandom()));
  final pair = keyGen.generateKeyPair();
  return Secp256k1PrivateKey.fromPointyCastle(pair.privateKey);
}

pc.SecureRandom _secureRandom() {
  final dartRng = Random.secure();
  final rng = pc.FortunaRandom();
  rng.seed(
    pc.KeyParameter(
      Uint8List.fromList(List<int>.generate(32, (_) => dartRng.nextInt(256))),
    ),
  );
  return rng;
}

/// Parses a raw 32-byte big-endian Secp256k1 private key, per go-libp2p's
/// `UnmarshalSecp256k1PrivateKey`.
Secp256k1PrivateKey unmarshalSecp256k1PrivateKey(Uint8List data) {
  if (data.length != 32) {
    throw FormatException('expected secp256k1 data size to be 32, got ${data.length}');
  }
  final d = _decodeUnsigned(data);
  if (d == BigInt.zero || d >= _params.n) {
    throw const FormatException('secp256k1 private key out of range');
  }
  return Secp256k1PrivateKey.fromPointyCastle(pc.ECPrivateKey(d, _params));
}

/// Parses a SEC1-encoded (compressed or uncompressed) Secp256k1 public
/// key, per go-libp2p's `UnmarshalSecp256k1PublicKey`.
Secp256k1PublicKey unmarshalSecp256k1PublicKey(Uint8List data) {
  final point = _params.curve.decodePoint(data);
  if (point == null) {
    throw const FormatException('malformed secp256k1 public key');
  }
  return Secp256k1PublicKey.fromPointyCastle(pc.ECPublicKey(point, _params));
}

Uint8List _encodeFixed32(BigInt value) {
  final out = Uint8List(32);
  var v = value;
  for (var i = 31; i >= 0; i--) {
    out[i] = (v & BigInt.from(0xff)).toInt();
    v = v >> 8;
  }
  return out;
}

BigInt _decodeUnsigned(Uint8List bytes) {
  var result = BigInt.zero;
  for (final byte in bytes) {
    result = (result << 8) | BigInt.from(byte);
  }
  return result;
}

/// DER `SEQUENCE { INTEGER r, INTEGER s }`, matching dcrd's
/// `Signature.Serialize()`.
Uint8List _encodeDerSignature(pc.ECSignature sig) {
  final seq = ASN1Sequence(
    elements: [ASN1Integer(sig.r), ASN1Integer(sig.s)],
  );
  return seq.encode();
}

pc.ECSignature _decodeDerSignature(Uint8List der) {
  final seq = ASN1Sequence.fromBytes(der);
  final elements = seq.elements!;
  if (elements.length < 2) {
    throw const FormatException('malformed ECDSA DER signature');
  }
  final r = (elements[0] as ASN1Integer).integer!;
  final s = (elements[1] as ASN1Integer).integer!;
  return pc.ECSignature(r, s);
}
