// ignore_for_file: duplicate_ignore, public_member_api_docs, sort_constructors_first, directives_ordering, dangling_library_doc_comments, library_prefixes, constant_identifier_names, depend_on_referenced_packages
// lib/src/crypto/ecdsa_key.dart
//
// Port of go-libp2p's core/crypto ECDSA support (core/crypto/ecdsa.go),
// which is hardcoded to NIST P-256 (`elliptic.P256()`). Raw private keys
// are SEC1 EC private keys (RFC 5915, `x509.MarshalECPrivateKey`/
// `ParseECPrivateKey`); raw public keys are PKIX `SubjectPublicKeyInfo`
// (`x509.MarshalPKIXPublicKey`/`ParsePKIXPublicKey`) wrapping an
// uncompressed SEC1 point; signatures are ASN.1 `SEQUENCE{R,S}` over a
// SHA-256 digest, matching `ecdsa.Sign`/`ecdsa.Verify`.
//
// Verified against a real key/signature generated by Go's crypto/ecdsa +
// crypto/x509 (go-ipfs-reference/ecdsa_vectors/main.go) -- see
// test/ecdsa_key_parity_test.dart. Go's `ecdsa.Sign` uses randomized
// (non-deterministic) nonces, so parity here is proven by cross
// verification rather than a byte-identical signature.
import 'dart:math' show Random;
import 'dart:typed_data';

import 'package:pointycastle/asn1.dart';
import 'package:pointycastle/export.dart' as pc;

import 'key_types.dart';

final pc.ECDomainParameters _params = pc.ECCurve_secp256r1();

/// PKIX's `id-ecPublicKey` OID (1.2.840.10045.2.1).
const List<int> _ecPublicKeyOid = [1, 2, 840, 10045, 2, 1];

/// The NIST P-256 / secp256r1 / prime256v1 named-curve OID
/// (1.2.840.10045.3.1.7) -- the only curve go-libp2p's ECDSA key type
/// generates.
const List<int> _prime256v1Oid = [1, 2, 840, 10045, 3, 1, 7];

/// An ECDSA (NIST P-256) private key, per go-libp2p's `core/crypto`
/// `ECDSAPrivateKey`.
class EcdsaPrivateKey extends PrivKey {
  EcdsaPrivateKey._(this._key, this._public);

  /// Wraps an already-parsed pointycastle EC private key.
  factory EcdsaPrivateKey.fromPointyCastle(pc.ECPrivateKey key) {
    final q = (_params.G * key.d!)!;
    return EcdsaPrivateKey._(key, EcdsaPublicKey.fromPointyCastle(pc.ECPublicKey(q, _params)));
  }

  final pc.ECPrivateKey _key;
  final EcdsaPublicKey _public;

  @override
  KeyType get type => KeyType.ecdsa;

  @override
  PubKey getPublic() => _public;

  @override
  Uint8List raw() => encodeSec1EcPrivateKey(_key, _public._key);

  @override
  Future<Uint8List> sign(Uint8List data) async {
    final signer = pc.ECDSASigner(pc.SHA256Digest())
      ..init(
        true,
        pc.ParametersWithRandom(
          pc.PrivateKeyParameter<pc.ECPrivateKey>(_key),
          _secureRandom(),
        ),
      );
    final sig = signer.generateSignature(data) as pc.ECSignature;
    return _encodeDerSignature(sig);
  }
}

/// An ECDSA (NIST P-256) public key, per go-libp2p's `core/crypto`
/// `ECDSAPublicKey`.
class EcdsaPublicKey extends PubKey {
  EcdsaPublicKey._(this._key);

  /// Wraps an already-parsed pointycastle EC public key.
  factory EcdsaPublicKey.fromPointyCastle(pc.ECPublicKey key) => EcdsaPublicKey._(key);

  final pc.ECPublicKey _key;

  @override
  KeyType get type => KeyType.ecdsa;

  @override
  Uint8List raw() => encodePkixEcPublicKey(_key);

  @override
  Future<bool> verify(Uint8List data, Uint8List signature) async {
    final pc.ECSignature sig;
    try {
      sig = _decodeDerSignature(signature);
    } on FormatException {
      return false;
    }
    final signer = pc.ECDSASigner(pc.SHA256Digest())
      ..init(false, pc.PublicKeyParameter<pc.ECPublicKey>(_key));
    return signer.verifySignature(data, sig);
  }
}

/// Generates a fresh NIST P-256 ECDSA key pair, per go-libp2p's
/// `GenerateECDSAKeyPair`.
EcdsaPrivateKey generateEcdsaKeyPair() {
  final keyGen = pc.ECKeyGenerator()
    ..init(pc.ParametersWithRandom(pc.ECKeyGeneratorParameters(_params), _secureRandom()));
  final pair = keyGen.generateKeyPair();
  return EcdsaPrivateKey.fromPointyCastle(pair.privateKey);
}

pc.SecureRandom _secureRandom() {
  final dartRng = Random.secure();
  final rng = pc.FortunaRandom();
  rng.seed(
    pc.KeyParameter(
      Uint8List.fromList(List<int>.generate(32, (_) => dartRng.nextInt(256))),
    ),
  );
  return rng;
}

/// Parses a SEC1 (RFC 5915) EC private key, per go-libp2p's
/// `UnmarshalECDSAPrivateKey` (`x509.ParseECPrivateKey`).
EcdsaPrivateKey unmarshalEcdsaPrivateKey(Uint8List der) {
  final seq = ASN1Sequence.fromBytes(der);
  final elements = seq.elements!;
  if (elements.length < 2) {
    throw const FormatException('malformed SEC1 EC private key');
  }
  final version = (elements[0] as ASN1Integer).integer!;
  if (version != BigInt.one) {
    throw FormatException('unsupported EC private key version: $version');
  }
  final d = _decodeUnsigned((elements[1] as ASN1OctetString).octets!);

  pc.ECPoint? q;
  for (final el in elements.skip(2)) {
    if (el.tag == 0xA0) {
      final oid = ASN1ObjectIdentifier.fromBytes(el.valueBytes!);
      if (oid.objectIdentifierAsString != _prime256v1Oid.join('.')) {
        throw FormatException('unsupported EC curve OID: ${oid.objectIdentifierAsString}');
      }
    } else if (el.tag == 0xA1) {
      final bitString = ASN1BitString.fromBytes(el.valueBytes!);
      q = _params.curve.decodePoint(bitString.stringValues!);
    }
  }
  q ??= (_params.G * d)!;

  return EcdsaPrivateKey._(
    pc.ECPrivateKey(d, _params),
    EcdsaPublicKey.fromPointyCastle(pc.ECPublicKey(q, _params)),
  );
}

/// Parses a PKIX-DER EC public key (`SubjectPublicKeyInfo`), per
/// go-libp2p's `UnmarshalECDSAPublicKey` (`x509.ParsePKIXPublicKey`).
EcdsaPublicKey unmarshalEcdsaPublicKey(Uint8List der) {
  final outer = ASN1Sequence.fromBytes(der);
  final elements = outer.elements!;
  if (elements.length < 2) {
    throw const FormatException('malformed PKIX EC public key');
  }
  final algId = elements[0] as ASN1Sequence;
  final algOid = (algId.elements![0] as ASN1ObjectIdentifier).objectIdentifierAsString;
  if (algOid != _ecPublicKeyOid.join('.')) {
    throw FormatException('not an EC public key (algorithm OID $algOid)');
  }
  final curveOid = (algId.elements![1] as ASN1ObjectIdentifier).objectIdentifierAsString;
  if (curveOid != _prime256v1Oid.join('.')) {
    throw FormatException('unsupported EC curve OID: $curveOid');
  }
  final bitString = elements[1] as ASN1BitString;
  final point = _params.curve.decodePoint(bitString.stringValues!);
  if (point == null) {
    throw const FormatException('malformed EC point');
  }
  return EcdsaPublicKey.fromPointyCastle(pc.ECPublicKey(point, _params));
}

/// Encodes a SEC1 (RFC 5915) `ECPrivateKey` DER structure, matching
/// `x509.MarshalECPrivateKey`.
Uint8List encodeSec1EcPrivateKey(pc.ECPrivateKey key, pc.ECPublicKey pub) {
  final namedCurveTag = ASN1Object(tag: 0xA0)
    ..valueBytes = ASN1ObjectIdentifier(_prime256v1Oid).encode();
  final publicKeyTag = ASN1Object(tag: 0xA1)
    ..valueBytes = (ASN1BitString(stringValues: pub.Q!.getEncoded(false))..unusedbits = 0).encode();

  final seq = ASN1Sequence(
    elements: [
      ASN1Integer(BigInt.one),
      ASN1OctetString(octets: _encodeFixed32(key.d!)),
      namedCurveTag,
      publicKeyTag,
    ],
  );
  return seq.encode();
}

/// Encodes a PKIX `SubjectPublicKeyInfo` DER structure wrapping an
/// uncompressed EC point, matching `x509.MarshalPKIXPublicKey`.
Uint8List encodePkixEcPublicKey(pc.ECPublicKey key) {
  final algorithmId = ASN1Sequence(
    elements: [
      ASN1ObjectIdentifier(_ecPublicKeyOid),
      ASN1ObjectIdentifier(_prime256v1Oid),
    ],
  );
  final bitString = ASN1BitString(stringValues: key.Q!.getEncoded(false))..unusedbits = 0;
  final outer = ASN1Sequence(elements: [algorithmId, bitString]);
  return outer.encode();
}

Uint8List _encodeFixed32(BigInt value) {
  final out = Uint8List(32);
  var v = value;
  for (var i = 31; i >= 0; i--) {
    out[i] = (v & BigInt.from(0xff)).toInt();
    v = v >> 8;
  }
  return out;
}

BigInt _decodeUnsigned(Uint8List bytes) {
  var result = BigInt.zero;
  for (final byte in bytes) {
    result = (result << 8) | BigInt.from(byte);
  }
  return result;
}

/// DER `SEQUENCE { INTEGER r, INTEGER s }`, matching Go's
/// `asn1.Marshal(ECDSASig{R, S})`.
Uint8List _encodeDerSignature(pc.ECSignature sig) {
  final seq = ASN1Sequence(elements: [ASN1Integer(sig.r), ASN1Integer(sig.s)]);
  return seq.encode();
}

pc.ECSignature _decodeDerSignature(Uint8List der) {
  final seq = ASN1Sequence.fromBytes(der);
  final elements = seq.elements!;
  if (elements.length < 2) {
    throw const FormatException('malformed ECDSA DER signature');
  }
  final r = (elements[0] as ASN1Integer).integer!;
  final s = (elements[1] as ASN1Integer).integer!;
  return pc.ECSignature(r, s);
}
