// ignore_for_file: duplicate_ignore, public_member_api_docs, sort_constructors_first, directives_ordering, dangling_library_doc_comments, library_prefixes, constant_identifier_names, depend_on_referenced_packages
// lib/src/crypto/rsa_key.dart
//
// Port of go-libp2p's core/crypto RSA support (core/crypto/rsa_go.go,
// rsa_common.go): PKCS1-DER private keys, PKIX-DER (SubjectPublicKeyInfo)
// public keys, SHA-256/PKCS1v1.5 signatures -- matching
// `x509.MarshalPKCS1PrivateKey`/`x509.MarshalPKIXPublicKey`/
// `rsa.SignPKCS1v15`/`rsa.VerifyPKCS1v15` exactly, so keys and signatures
// interoperate with real go-libp2p peers.
//
// Verified byte-for-byte against a real key generated by Go's crypto/rsa +
// crypto/x509 (go-ipfs-reference/noise_vectors/rsa_vectors.go) -- see
// test/rsa_key_parity_test.dart.
import 'dart:math' show Random;
import 'dart:typed_data';

import 'package:pointycastle/asn1.dart';
import 'package:pointycastle/export.dart' as pc;

import 'key_types.dart';

/// The minimum RSA key size go-libp2p accepts, per core/crypto/
/// rsa_common.go's default `MinRsaKeyBits`.
const int minRsaKeyBits = 2048;

/// PKCS#1's `rsaEncryption` OID (1.2.840.113549.1.1.1), used in a PKIX
/// `SubjectPublicKeyInfo`'s `AlgorithmIdentifier`.
const List<int> _rsaEncryptionOid = [1, 2, 840, 113549, 1, 1, 1];

/// SHA-256's OID DER encoding, as `RSASigner` expects it (see
/// `package:pointycastle`'s `RSASigner._digestIdentifierHexes['SHA-256']`).
const String _sha256DigestOidHex = '0609608648016503040201';

/// An RSA private key, per go-libp2p's `core/crypto` `RsaPrivateKey`.
class RsaPrivateKey extends PrivKey {
  RsaPrivateKey._(this._key, this._public);

  /// Wraps an already-parsed pointycastle RSA private key.
  factory RsaPrivateKey.fromPointyCastle(pc.RSAPrivateKey key) {
    final pub = pc.RSAPublicKey(key.modulus!, key.publicExponent!);
    return RsaPrivateKey._(key, RsaPublicKey.fromPointyCastle(pub));
  }

  final pc.RSAPrivateKey _key;
  final RsaPublicKey _public;

  @override
  KeyType get type => KeyType.rsa;

  @override
  PubKey getPublic() => _public;

  @override
  Uint8List raw() => encodePkcs1PrivateKey(_key);

  @override
  Future<Uint8List> sign(Uint8List data) async {
    final signer = pc.RSASigner(pc.SHA256Digest(), _sha256DigestOidHex)
      ..init(true, pc.PrivateKeyParameter<pc.RSAPrivateKey>(_key));
    return signer.generateSignature(data).bytes;
  }
}

/// An RSA public key, per go-libp2p's `core/crypto` `RsaPublicKey`.
class RsaPublicKey extends PubKey {
  RsaPublicKey._(this._key);

  /// Wraps an already-parsed pointycastle RSA public key.
  factory RsaPublicKey.fromPointyCastle(pc.RSAPublicKey key) =>
      RsaPublicKey._(key);

  final pc.RSAPublicKey _key;

  @override
  KeyType get type => KeyType.rsa;

  @override
  Uint8List raw() => encodePkixPublicKey(_key);

  @override
  Future<bool> verify(Uint8List data, Uint8List signature) async {
    final signer = pc.RSASigner(pc.SHA256Digest(), _sha256DigestOidHex)
      ..init(false, pc.PublicKeyParameter<pc.RSAPublicKey>(_key));
    try {
      return signer.verifySignature(data, pc.RSASignature(signature));
    } on ArgumentError {
      // Malformed signature bytes that don't even parse as a PKCS1 block.
      return false;
    }
  }
}

/// Generates a fresh RSA key pair with [bits] modulus size (must be at
/// least [minRsaKeyBits], per go-libp2p's own `GenerateRSAKeyPair`).
RsaPrivateKey generateRsaKeyPair(int bits) {
  if (bits < minRsaKeyBits) {
    throw ArgumentError('RSA key too small: $bits < $minRsaKeyBits bits');
  }
  final keyGen = pc.RSAKeyGenerator()
    ..init(
      pc.ParametersWithRandom(
        pc.RSAKeyGeneratorParameters(BigInt.from(65537), bits, 64),
        _secureRandom(),
      ),
    );
  final pair = keyGen.generateKeyPair();
  return RsaPrivateKey.fromPointyCastle(pair.privateKey);
}

pc.SecureRandom _secureRandom() {
  final dartRng = Random.secure();
  final rng = pc.FortunaRandom();
  rng.seed(
    pc.KeyParameter(
      Uint8List.fromList(List<int>.generate(32, (_) => dartRng.nextInt(256))),
    ),
  );
  return rng;
}

/// Parses an X.509/PKCS1-DER-encoded RSA private key, per go-libp2p's
/// `UnmarshalRsaPrivateKey` (`x509.ParsePKCS1PrivateKey`).
RsaPrivateKey unmarshalRsaPrivateKey(Uint8List der) {
  final seq = ASN1Sequence.fromBytes(der);
  final elements = seq.elements!;
  // RSAPrivateKey ::= SEQUENCE { version, n, e, d, p, q, dP, dQ, qInv, ... }
  if (elements.length < 9) {
    throw const FormatException('malformed PKCS1 RSA private key');
  }
  BigInt intAt(int i) => (elements[i] as ASN1Integer).integer!;
  final n = intAt(1);
  final d = intAt(3);
  final p = intAt(4);
  final q = intAt(5);
  final key = pc.RSAPrivateKey(n, d, p, q);
  if (key.modulus!.bitLength < minRsaKeyBits) {
    throw FormatException(
      'RSA key too small: ${key.modulus!.bitLength} < $minRsaKeyBits bits',
    );
  }
  return RsaPrivateKey.fromPointyCastle(key);
}

/// Parses an X.509/PKIX-DER-encoded RSA public key
/// (`SubjectPublicKeyInfo`), per go-libp2p's `UnmarshalRsaPublicKey`
/// (`x509.ParsePKIXPublicKey`).
RsaPublicKey unmarshalRsaPublicKey(Uint8List der) {
  final outer = ASN1Sequence.fromBytes(der);
  if (outer.elements!.length < 2) {
    throw const FormatException('malformed PKIX public key');
  }
  final bitString = outer.elements![1] as ASN1BitString;
  final inner = ASN1Sequence.fromBytes(
    Uint8List.fromList(bitString.stringValues!),
  );
  if (inner.elements!.length < 2) {
    throw const FormatException('malformed PKCS1 RSA public key');
  }
  final n = (inner.elements![0] as ASN1Integer).integer!;
  final e = (inner.elements![1] as ASN1Integer).integer!;
  if (n.bitLength < minRsaKeyBits) {
    throw FormatException(
      'RSA key too small: ${n.bitLength} < $minRsaKeyBits bits',
    );
  }
  return RsaPublicKey.fromPointyCastle(pc.RSAPublicKey(n, e));
}

/// Encodes a PKCS1 `RSAPrivateKey` DER structure (RFC 8017 appendix
/// A.1.2), matching `x509.MarshalPKCS1PrivateKey`.
Uint8List encodePkcs1PrivateKey(pc.RSAPrivateKey key) {
  final n = key.modulus!;
  final d = key.privateExponent!;
  final p = key.p!;
  final q = key.q!;
  final e = key.publicExponent!;
  final dP = d % (p - BigInt.one);
  final dQ = d % (q - BigInt.one);
  final qInv = q.modInverse(p);

  final seq = ASN1Sequence(
    elements: [
      ASN1Integer(BigInt.zero), // version
      ASN1Integer(n),
      ASN1Integer(e),
      ASN1Integer(d),
      ASN1Integer(p),
      ASN1Integer(q),
      ASN1Integer(dP),
      ASN1Integer(dQ),
      ASN1Integer(qInv),
    ],
  );
  return seq.encode();
}

/// Encodes a PKIX `SubjectPublicKeyInfo` DER structure wrapping a PKCS1
/// `RSAPublicKey` (RFC 5280 / RFC 8017), matching
/// `x509.MarshalPKIXPublicKey`.
Uint8List encodePkixPublicKey(pc.RSAPublicKey key) {
  final inner = ASN1Sequence(
    elements: [
      ASN1Integer(key.modulus!),
      ASN1Integer(key.publicExponent!),
    ],
  ).encode();

  final algorithmId = ASN1Sequence(
    elements: [ASN1ObjectIdentifier(_rsaEncryptionOid), ASN1Null()],
  );
  final bitString = ASN1BitString(stringValues: inner)..unusedbits = 0;

  final outer = ASN1Sequence(elements: [algorithmId, bitString]);
  return outer.encode();
}
