// tool/generate_prefix_map.dart
//
// Port of go-libp2p-kbucket's generate/main.go: for each of the 65536
// possible 16-bit prefixes, finds the smallest counter `i` such that
// sha2-256(identity-multihash-prefix ++ BigEndian32(i))'s own first 16
// bits equal that prefix, and writes the resulting `i` values to
// lib/src/key_prefix_map.dart.
//
// This produces the exact same table as the Go generator: same hash
// function, same input encoding, same "first i found, scanning upward"
// search order -- so the two tables are byte-for-byte identical, which
// is checked directly in test/key_prefix_map_test.dart against a sample
// of real values copied from go-libp2p-kbucket's own generated file.
//
// Run with: dart run tool/generate_prefix_map.dart
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:crypto/crypto.dart';

const _bits = 16;
const _target = 1 << _bits;
const _idLen = 32 + 2;

void main() {
  final ids = Uint32List(_target);
  final found = List<bool>.filled(_target, false);
  var count = 0;

  // Matches Go's `inp := [idLen]byte{mh.SHA2_256, 32}`: a 34-byte buffer
  // (2-byte multihash header + a 32-byte digest-shaped payload), with the
  // counter written into the first 4 bytes of that payload and the
  // remaining 28 bytes left zero -- the *whole* 34 bytes get hashed, not
  // just the header+counter.
  final input = Uint8List(_idLen)
    ..[0] = 0x12 // multihash code: sha2-256
    ..[1] = 0x20; // multihash digest length: 32 bytes

  for (var i = 0; count < _target; i++) {
    input.buffer.asByteData().setUint32(2, i, Endian.big);
    final digest = sha256.convert(input).bytes;
    final digestPrefix =
        ((digest[0] << 24) | (digest[1] << 16) | (digest[2] << 8) | digest[3]) >>
            (32 - _bits);
    if (!found[digestPrefix]) {
      found[digestPrefix] = true;
      ids[digestPrefix] = i;
      count++;
    }
  }

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/generate_prefix_map.dart -- DO NOT EDIT.')
    ..writeln('//')
    ..writeln('// Port of go-libp2p-kbucket\'s generated bucket_prefixmap.go: for')
    ..writeln('// each 16-bit prefix p, keyPrefixMap[p] is the smallest counter i')
    ..writeln('// such that sha2-256({0x12, 0x20} ++ BigEndian32(i)) itself starts')
    ..writeln('// with the 16 bits of p. See tool/generate_prefix_map.dart.')
    ..writeln()
    ..writeln('/// See this file\'s header comment.')
    ..writeln('const List<int> keyPrefixMap = [');
  for (var i = 0; i < _target; i += 16) {
    buffer.write('  ');
    buffer.writeln(
      ids.sublist(i, i + 16).map((v) => '$v,').join(' '),
    );
  }
  buffer.writeln('];');

  final outFile = File(
    '${Directory.current.path}/lib/src/key_prefix_map.dart',
  );
  outFile.writeAsStringSync(buffer.toString(), encoding: utf8);
  stdout.writeln('Wrote ${outFile.path}');
}
