// lib/src/transport/noise/noise_state.dart
//
// Port of the Noise Protocol Framework core (http://noiseprotocol.org/
// noise.html, sections 4-5) as used by go-libp2p's noise-libp2p security
// transport (p2p/security/noise): the fixed cipher suite `DH25519,
// CipherChaChaPoly, HashSHA256` and the fixed `XX` handshake pattern
// (`-> e`, `<- e, ee, s, es`, `-> s, se`). This isn't a general Noise
// library -- go-libp2p never uses another pattern or cipher suite, so
// there's no reason to build one.
//
// Verified byte-for-byte against real vectors generated by flynn/noise
// (the actual Go library go-libp2p's own noise transport depends on) via
// its own vectorgen tool, for the exact
// `Noise_XX_25519_ChaChaPoly_SHA256` combination with a prologue and
// payloads -- see test/transport/noise/noise_state_test.dart.
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';

/// `Noise_XX_25519_ChaChaPoly_SHA256`'s protocol name, per spec section
/// 8: used to initialize the handshake hash when it's <=32 bytes (it's
/// not, here, so [_initializeHash] falls through to hashing it).
const String noiseProtocolName = 'Noise_XX_25519_ChaChaPoly_SHA256';

const int _hashLen = 32; // SHA256 digest length.
const int _dhLen = 32; // X25519 key length.

final Sha256 _sha256 = Sha256();
final X25519 _x25519 = X25519();
final Chacha20 _chacha20Poly1305 = Chacha20.poly1305Aead();

Future<Uint8List> _hmacSha256(Uint8List key, Uint8List data) async {
  final mac = await Hmac.sha256().calculateMac(data, secretKey: SecretKey(key));
  return Uint8List.fromList(mac.bytes);
}

/// Noise's own 2-or-3-output HKDF (spec section 4.3) -- similar to but
/// distinct from RFC 5869's construction, so this is hand-rolled over raw
/// HMAC-SHA256 rather than reusing `package:cryptography`'s `Hkdf` (which
/// implements RFC 5869 exactly).
Future<List<Uint8List>> _noiseHkdf(
  Uint8List chainingKey,
  Uint8List inputKeyMaterial, {
  required int numOutputs,
}) async {
  final tempKey = await _hmacSha256(chainingKey, inputKeyMaterial);
  final output1 = await _hmacSha256(tempKey, Uint8List.fromList([0x01]));
  if (numOutputs == 1) return [output1];
  final output2 = await _hmacSha256(
    tempKey,
    Uint8List.fromList([...output1, 0x02]),
  );
  if (numOutputs == 2) return [output1, output2];
  final output3 = await _hmacSha256(
    tempKey,
    Uint8List.fromList([...output2, 0x03]),
  );
  return [output1, output2, output3];
}

Uint8List _concat(List<int> a, List<int> b) =>
    Uint8List.fromList([...a, ...b]);

/// A Noise DH key pair: [privateKeyBytes] is the raw 32-byte X25519 scalar
/// (pre-clamping seed, matching flynn/noise's `DHKey.Private`), and
/// [publicKeyBytes] its corresponding public key.
class NoiseKeyPair {
  /// Builds a key pair from its raw scalar/point bytes.
  const NoiseKeyPair({
    required this.privateKeyBytes,
    required this.publicKeyBytes,
  });

  /// The raw 32-byte X25519 private scalar (pre-clamping seed).
  final Uint8List privateKeyBytes;

  /// The corresponding X25519 public key.
  final Uint8List publicKeyBytes;

  Future<SimpleKeyPair> _asCryptographyKeyPair() =>
      _x25519.newKeyPairFromSeed(privateKeyBytes);
}

/// Generates a fresh X25519 key pair (used for both the Noise static key
/// and, per handshake, a fresh ephemeral key).
Future<NoiseKeyPair> generateNoiseKeyPair() async {
  final kp = await _x25519.newKeyPair();
  final priv = await kp.extractPrivateKeyBytes();
  final pub = await kp.extractPublicKey();
  return NoiseKeyPair(
    privateKeyBytes: Uint8List.fromList(priv),
    publicKeyBytes: Uint8List.fromList(pub.bytes),
  );
}

Future<Uint8List> _dh(NoiseKeyPair local, Uint8List remotePublicKey) async {
  final localKeyPair = await local._asCryptographyKeyPair();
  final shared = await _x25519.sharedSecretKey(
    keyPair: localKeyPair,
    remotePublicKey: SimplePublicKey(
      remotePublicKey,
      type: KeyPairType.x25519,
    ),
  );
  return Uint8List.fromList(await shared.extractBytes());
}

/// Noise spec section 5.1: `k` (32-byte key, or absent) and `n` (64-bit
/// nonce counter).
class CipherState {
  /// Builds a cipher state, optionally already keyed.
  CipherState({Uint8List? key}) : _key = key, _nonce = 0;

  Uint8List? _key;
  int _nonce;

  /// Whether a key has been established yet.
  bool get hasKey => _key != null;

  /// The raw 32-byte symmetric key, once established (`null` before
  /// then). Exposed so post-handshake transport wrappers that do their
  /// own AEAD framing (e.g. reusing an existing `TransportConn`-style
  /// connection wrapper instead of this class's own encrypt/decrypt)
  /// can seed themselves from this `CipherState`'s derived key.
  Uint8List? get keyBytes => _key;

  /// Sets (or replaces) the key and resets the nonce counter to 0.
  void initializeKey(Uint8List key) {
    _key = key;
    _nonce = 0;
  }

  /// `EncryptWithAd`: returns `plaintext` unmodified if no key is set yet
  /// (spec section 5.1), otherwise ChaCha20-Poly1305-AEAD-encrypts it
  /// (ciphertext with a 16-byte tag appended) under the current key/nonce,
  /// then increments the nonce.
  Future<Uint8List> encryptWithAd(Uint8List ad, Uint8List plaintext) async {
    final key = _key;
    if (key == null) return plaintext;
    final nonceBytes = _nonceBytes(_nonce);
    final box = await _chacha20Poly1305.encrypt(
      plaintext,
      secretKey: SecretKey(key),
      nonce: nonceBytes,
      aad: ad,
    );
    _nonce += 1;
    return Uint8List.fromList([...box.cipherText, ...box.mac.bytes]);
  }

  /// `DecryptWithAd`: mirrors [encryptWithAd].
  Future<Uint8List> decryptWithAd(Uint8List ad, Uint8List ciphertext) async {
    final key = _key;
    if (key == null) return ciphertext;
    if (ciphertext.length < 16) {
      throw const FormatException('Noise ciphertext shorter than the MAC tag');
    }
    final nonceBytes = _nonceBytes(_nonce);
    final box = SecretBox(
      ciphertext.sublist(0, ciphertext.length - 16),
      nonce: nonceBytes,
      mac: Mac(ciphertext.sublist(ciphertext.length - 16)),
    );
    final plaintext = await _chacha20Poly1305.decrypt(
      box,
      secretKey: SecretKey(key),
      aad: ad,
    );
    _nonce += 1;
    return Uint8List.fromList(plaintext);
  }

  /// ChaChaPoly's 96-bit (12-byte) nonce, per the Noise spec's mapping of
  /// its 64-bit nonce counter for ChaCha20-Poly1305: 4 zero bytes followed
  /// by the little-endian 8-byte counter.
  static Uint8List _nonceBytes(int n) {
    final b = ByteData(12);
    b.setUint64(4, n, Endian.little);
    return b.buffer.asUint8List();
  }
}

/// Noise spec section 5.2: `ck` (chaining key), `h` (handshake hash), and
/// the symmetric [CipherState] derived from them once a DH result is
/// mixed in.
class SymmetricState {
  SymmetricState._(this._chainingKey, this._h) : cipherState = CipherState();

  /// Initializes `ck`/`h` from [protocolName] (spec section 5.2's
  /// `InitializeSymmetric`).
  static Future<SymmetricState> initialize(String protocolName) async {
    final nameBytes = Uint8List.fromList(protocolName.codeUnits);
    final Uint8List h;
    if (nameBytes.length <= _hashLen) {
      h = Uint8List(_hashLen)..setRange(0, nameBytes.length, nameBytes);
    } else {
      h = Uint8List.fromList((await _sha256.hash(nameBytes)).bytes);
    }
    return SymmetricState._(Uint8List.fromList(h), h);
  }

  Uint8List _chainingKey;
  Uint8List _h;

  /// The symmetric cipher state derived from the chaining key so far.
  final CipherState cipherState;

  /// Mixes a DH output (or other input key material) into the chaining
  /// key and re-derives [cipherState]'s key from it.
  Future<void> mixKey(Uint8List inputKeyMaterial) async {
    final outputs = await _noiseHkdf(
      _chainingKey,
      inputKeyMaterial,
      numOutputs: 2,
    );
    _chainingKey = outputs[0];
    cipherState.initializeKey(outputs[1]);
  }

  /// Mixes [data] into the running handshake hash `h`.
  Future<void> mixHash(Uint8List data) async {
    _h = Uint8List.fromList((await _sha256.hash(_concat(_h, data))).bytes);
  }

  /// Encrypts (if a key is set) [plaintext] under the current handshake
  /// hash as associated data, then mixes the result into that hash.
  Future<Uint8List> encryptAndHash(Uint8List plaintext) async {
    final ciphertext = await cipherState.encryptWithAd(_h, plaintext);
    await mixHash(ciphertext);
    return ciphertext;
  }

  /// Mirrors [encryptAndHash] for the receiving side.
  Future<Uint8List> decryptAndHash(Uint8List ciphertext) async {
    final plaintext = await cipherState.decryptWithAd(_h, ciphertext);
    await mixHash(ciphertext);
    return plaintext;
  }

  /// Spec section 5.3 `Split()`: derives the two directional
  /// [CipherState]s from the final chaining key, once the handshake's
  /// message patterns are exhausted.
  Future<(CipherState, CipherState)> split() async {
    final outputs = await _noiseHkdf(
      _chainingKey,
      Uint8List(0),
      numOutputs: 2,
    );
    return (CipherState(key: outputs[0]), CipherState(key: outputs[1]));
  }
}

/// One handshake message's token sequence. XX's three messages:
/// `-> e`, `<- e, ee, s, es`, `-> s, se`.
enum _Token { e, s, ee, es, se }

const List<List<_Token>> _xxPattern = [
  [_Token.e],
  [_Token.e, _Token.ee, _Token.s, _Token.es],
  [_Token.s, _Token.se],
];

/// Drives one side of a `Noise_XX_25519_ChaChaPoly_SHA256` handshake.
/// Equivalent to go-libp2p's use of `flynn/noise`'s `HandshakeState`
/// (`noise.NewHandshakeState` with `Pattern: noise.HandshakeXX`).
class HandshakeState {
  HandshakeState._(
    this.initiator,
    SymmetricState symmetricState,
    NoiseKeyPair staticKeyPair,
    Future<NoiseKeyPair> Function() ephemeralKeyGenerator,
  ) : _symmetricState = symmetricState,
      _s = staticKeyPair,
      _ephemeralKeyGenerator = ephemeralKeyGenerator;

  /// Starts a handshake as [initiator] or responder, using [staticKeyPair]
  /// as this side's long-term Noise static key and [prologue] (if any) as
  /// out-of-band data both sides commit to before any messages are
  /// exchanged.
  ///
  /// [ephemeralKeyGenerator] produces this side's fresh per-handshake
  /// ephemeral key; defaults to [generateNoiseKeyPair]. Overriding it is
  /// only for reproducing fixed test vectors (mirrors flynn/noise's own
  /// `Config.Random`, which go-libp2p's noise transport never overrides in
  /// production either) -- real handshakes must always use a fresh random
  /// key.
  static Future<HandshakeState> initialize({
    required bool initiator,
    required NoiseKeyPair staticKeyPair,
    Uint8List? prologue,
    Future<NoiseKeyPair> Function() ephemeralKeyGenerator =
        generateNoiseKeyPair,
  }) async {
    final symmetricState = await SymmetricState.initialize(noiseProtocolName);
    await symmetricState.mixHash(prologue ?? Uint8List(0));
    return HandshakeState._(
      initiator,
      symmetricState,
      staticKeyPair,
      ephemeralKeyGenerator,
    );
  }

  /// Whether this side sent the first handshake message.
  final bool initiator;
  final SymmetricState _symmetricState;
  final NoiseKeyPair _s;
  final Future<NoiseKeyPair> Function() _ephemeralKeyGenerator;
  NoiseKeyPair? _e;
  Uint8List? _rs;
  Uint8List? _re;
  int _messageIndex = 0;

  /// Writes the next handshake message (per [_xxPattern]), embedding
  /// [payload] (encrypted once a key has been established -- see
  /// [CipherState.encryptWithAd]). Returns the wire bytes to send, and
  /// once the pattern is exhausted, the two directional [CipherState]s
  /// from [SymmetricState.split] (`null` otherwise).
  Future<(Uint8List message, (CipherState, CipherState)? split)> writeMessage(
    Uint8List payload,
  ) async {
    if (_messageIndex >= _xxPattern.length) {
      throw StateError('handshake already complete');
    }
    final pattern = _xxPattern[_messageIndex];
    final out = BytesBuilder();

    for (final token in pattern) {
      switch (token) {
        case _Token.e:
          final e = await _ephemeralKeyGenerator();
          _e = e;
          out.add(e.publicKeyBytes);
          await _symmetricState.mixHash(e.publicKeyBytes);
        case _Token.s:
          out.add(await _symmetricState.encryptAndHash(_s.publicKeyBytes));
        case _Token.ee:
          await _symmetricState.mixKey(await _dh(_e!, _re!));
        case _Token.es:
          if (initiator) {
            await _symmetricState.mixKey(await _dh(_e!, _rs!));
          } else {
            await _symmetricState.mixKey(await _dh(_s, _re!));
          }
        case _Token.se:
          if (initiator) {
            await _symmetricState.mixKey(await _dh(_s, _re!));
          } else {
            await _symmetricState.mixKey(await _dh(_e!, _rs!));
          }
      }
    }

    out.add(await _symmetricState.encryptAndHash(payload));
    _messageIndex++;

    (CipherState, CipherState)? split;
    if (_messageIndex == _xxPattern.length) {
      split = await _symmetricState.split();
    }
    return (out.toBytes(), split);
  }

  /// Reads the next handshake message, mirroring [writeMessage]. Returns
  /// the decrypted payload, and the split cipher states once complete.
  Future<(Uint8List payload, (CipherState, CipherState)? split)> readMessage(
    Uint8List message,
  ) async {
    if (_messageIndex >= _xxPattern.length) {
      throw StateError('handshake already complete');
    }
    final pattern = _xxPattern[_messageIndex];
    var offset = 0;

    for (final token in pattern) {
      switch (token) {
        case _Token.e:
          if (offset + _dhLen > message.length) {
            throw const FormatException('Noise message truncated reading e');
          }
          _re = message.sublist(offset, offset + _dhLen);
          offset += _dhLen;
          await _symmetricState.mixHash(_re!);
        case _Token.s:
          final hasKey = _symmetricState.cipherState.hasKey;
          final len = hasKey ? _dhLen + 16 : _dhLen;
          if (offset + len > message.length) {
            throw const FormatException('Noise message truncated reading s');
          }
          _rs = await _symmetricState.decryptAndHash(
            message.sublist(offset, offset + len),
          );
          offset += len;
        case _Token.ee:
          await _symmetricState.mixKey(await _dh(_e!, _re!));
        case _Token.es:
          if (initiator) {
            await _symmetricState.mixKey(await _dh(_e!, _rs!));
          } else {
            await _symmetricState.mixKey(await _dh(_s, _re!));
          }
        case _Token.se:
          if (initiator) {
            await _symmetricState.mixKey(await _dh(_s, _re!));
          } else {
            await _symmetricState.mixKey(await _dh(_e!, _rs!));
          }
      }
    }

    final payload = await _symmetricState.decryptAndHash(
      message.sublist(offset),
    );
    _messageIndex++;

    (CipherState, CipherState)? split;
    if (_messageIndex == _xxPattern.length) {
      split = await _symmetricState.split();
    }
    return (payload, split);
  }

  /// The remote peer's static public key, available once message 2 (the
  /// pattern containing the responder's `s` token) has been processed.
  Uint8List? get remoteStaticKey => _rs;
}
