name: transpiled_multiaddr_dns
description: Port of multiformats/go-multiaddr-dns.
version: 0.1.0
publish_to: none
homepage: https://github.com/multiformats/go-multiaddr-dns

environment:
  sdk: ^3.10.0

dependencies:
  transpiled_multiaddr:
    path: ../transpiled_multiaddr

dev_dependencies:
  test: ^1.28.0
  lints: ^6.1.0
  very_good_analysis: ^10.1.0
  analyzer: ^14.1.0 # AST parsing for tool/generate_module_index.dart
